apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm-pgvector
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - postgres-cluster.yaml
  - service.yaml
  - sealed-secret.yaml
images:
  - name: ghcr.io/fhswf/litellm-pgvector
    newTag: v1.2.0 # x-release-please-version
