apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm-pgvector
resources:
  - configmap.yaml
  - deployment.yaml
  - postgres-cluster.yaml
  - service.yaml
images:
  - name: ghcr.io/fhswf/litellm-pgvector
    newTag: sha256:9ab2119b5654669e0539a617bc07e59bdd0ef6c0aca1ac00262aae34df69693c # x-release-please-version
