apiVersion: v1
kind: Service
metadata:
  name: litellm-pgvector
  labels:
    app.kubernetes.io/name: litellm-pgvector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: litellm-pgvector
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
