FROM mcr.microsoft.com/devcontainers/python:3-3.12-trixie

COPY --from=ghcr.io/astral-sh/uv:0.9.22 /uv /uvx /usr/local/bin/

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    postgresql-client \
    libxcb1 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*
