apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm-pgvector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fhswf/litellm-pgvector.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
